### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by bwallrich** [janjakubnanista/gulp-svg-to-jsx#1]
The example doesn't seems to work

node_modules/gulp-svg-to-jsx/node_modules/q/q.js:155
                throw e;
                ^

TypeError: callback is not a function
    at node_modules/gulp-svg-to-jsx/node_modules/svg-to-jsx/index.js:164:13
    at _fulfilled node_modules/gulp-svg-to-jsx/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (node_modules/gulp-svg-to-jsx/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (node_modules/gulp-svg-to-jsx/node_modules/q/q.js:816:13)
    atnode_modules/gulp-svg-to-jsx/node_modules/q/q.js:624:44
    at runSingle (node_modules/gulp-svg-to-jsx/node_modules/q/q.js:137:13)
    at flush (node_modules/gulp-svg-to-jsx/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by janjakubnanista** [comment]
Thanks!!! I am going to merge this as soon as I finish something work related!

**Comment by TheSecondPower** [comment]
@janjakubnanista How's the work-related thing coming? I was hoping bwallrich's PR could be merged soon.

**Comment by janjakubnanista** [comment]
@TheSecondPower oh my god I am so sorry! Totally forgot about this. Version 0.0.7 is now available
